# Generated by Django 3.2.3 on 2021-05-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0002_auto_20210527_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlRisco', models.FloatField()),
                ('lstAcoes', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Acao',
        ),
    ]
