# Generated by Django 3.2.3 on 2021-05-30 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0003_auto_20210530_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculoacao',
            name='id',
        ),
        migrations.RemoveField(
            model_name='calculoacao',
            name='lstAcoes',
        ),
        migrations.AddField(
            model_name='calculoacao',
            name='ID',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('IDCalculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acao', to='serverapp.calculoacao')),
            ],
        ),
    ]
