# Generated by Django 3.2.3 on 2021-05-30 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0004_auto_20210530_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='IDCalculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acao', to='serverapp.calculoacao'),
        ),
    ]
