# Generated by Django 3.2.3 on 2021-05-30 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0006_auto_20210530_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculoacao',
            name='dtFim',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='calculoacao',
            name='dtInicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
